--- #This is bootstrap for skynet servers
- hosts: kubernetes
  become: yes
  tasks: 
  - name: Add logrotate for 14 mins  in syslog
#this has to then start with the module name "lineinfile"
    lineinfile: 
      line: "10 * * * * /usr/sbi/logrotate --force /etc/logrotate.conf"
      path: /var/spool/cron/crontabs/root

