--- #This is bootstrap for skynet servers
- hosts: kubernetes
  become: yes
  tasks: 
  - name: install figlet 
    apt:
      name: figlet
      state: latest
  - name: cloning git repo for lolcat
    shell: sudo git clone https://github.com/busyloop/lolcat && cd lolcat/bin && sudo gem install lolcat && cd /usr/share && sudo git clone https://github.com/xero/figlet-font && sudo mv figlet-fonts/* figlet && sudo rm –rf figlet-fonts      
  - name: Copy bashrc file with owner and permissions to root directory
    copy:
      src: /home/ansible/.bashrc
      dest: /home/root/
      owner: root
      group: root
      mode: '0644'
  - name: copy on-login.sh file to root location with owner and permissions
    copy:
      src: /home/ansible/.on-login.sh
      dest: /home/root/
      owner: root
      group: root
      mode: '0644'
  - name: command to figlet 
    shell: figlet -f Bloody "k8 test"
