--- #This is bootstrap for skynet servers
- hosts: sky2
  become: yes
  tasks: 
  - name: install apache2 on skynet2 servers
#this has to then start with the module name "apt G" 
    apt :
      name: apache2
      state: latest
  - name: Create a new index.html file
#this has to then start with the module name "file"
    file: 
      name: /var/www/html/index.html
      state: touch
  - name: Adding some content to index.html file
#this has to then start with the module name "lineinfile"
    lineinfile: 
      line: "These are skynet servers"
      path: /var/www/html/index.html
  - name: start the apache2 service
#this has to then start with the module name "service"
    service:
      name: apache2
      state: started

