--- #This is bootstrap for skynet servers
- hosts: sky2
  become: yes
  gather_facts: yes
  vars:
    target_service: apache2
  tasks:
  - debug: 
      var: target_service 
  - name: install apache2 on skynet2 servers
#this has to then start with the module name "apt G" 
    apt :
      name: "{{target_service}}"
      state: latest
    notify: 
      - restart apache2
  - name: Create a new index.html file
#this has to then start with the module name "file"
    file: 
      name: /var/www/html/index.html
      state: touch
  - name: Adding some content to index.html file
#this has to then start with the module name "lineinfile"
    lineinfile: 
      line: "{{ansible_hostname}}"
      path: /var/www/html/index.html
    notify:
      - restart apache2 
    register: task_debug
  - debug:
      msg: "Output of lineinfile is : {{task_debug}}"    
  handlers:
  - name: Attempt to restart the apache2
    service:
      name: "{{target_service}}"
      state: restarted
    listen: restart apache2
